services:
  - type: web
    name: rnj-ecommerce
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: rnj-postgres
          property: connectionString
    healthCheckPath: /api/health
    
databases:
  - name: rnj-postgres
    databaseName: rnj_ecommerce
    user: rnj_user
    
previewsEnabled: true
branch: main